import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';

export class GenerateTextResponseDto {
  @ApiProperty({
    description: 'Generated text content from the LLM.',
    example: 'Based on the policy, all changes require Dual Control approval.',
  })
  generatedText!: string;

  @ApiProperty({
    description: 'Identifier of the LLM model or endpoint that generated the response.',
    example: 'gini-llm-reasoning-dev (DeepSeek-R1-Distill-Llama-8B)',
  })
  model!: string;
}

export class GenerateEmbeddingResponseDto {
  @ApiProperty({
    description: 'Dense vector embedding floating point array.',
    example: [0.0241, -0.0152, 0.0891],
    type: [Number],
  })
  embedding!: number[];

  @ApiProperty({
    description: 'Dimensionality of the generated embedding vector.',
    example: 1024,
  })
  dimension!: number;
}

export class RetrievedChunkDto {
  @ApiProperty({
    description: 'Chunk identifier.',
    example: 'chunk-12345',
  })
  chunkId!: string;

  @ApiProperty({
    description: 'Parent document identifier.',
    example: 'doc-67890',
  })
  documentId!: string;

  @ApiProperty({
    description: 'Retrieved text passage.',
    example: 'Maker-Checker policy requires all mutation requests to be approved by a distinct Checker.',
  })
  text!: string;

  @ApiProperty({
    description: 'Relevance similarity score calculated by OpenSearch (k-NN / BM25 / RRF).',
    example: 0.892,
  })
  score!: number;

  @ApiPropertyOptional({
    description: 'Associated metadata attributes.',
    example: { page: 3, source: 'governance-policy.pdf' },
  })
  metadata?: Record<string, any>;
}

export class RagQueryResponseDto {
  @ApiProperty({
    description: 'Grounded answer generated by the LLM using the retrieved context.',
    example: 'To add a new identity provider, a Maker must submit the request, which then requires approval from an independent Checker.',
  })
  answer!: string;

  @ApiProperty({
    description: 'List of relevant source chunks retrieved from the tenant OpenSearch knowledge base.',
    type: [RetrievedChunkDto],
  })
  sources!: RetrievedChunkDto[];

  @ApiProperty({
    description: 'Search mode utilized for knowledge retrieval.',
    example: 'hybrid (k-NN + BM25)',
  })
  retrievalMode!: string;
}
